### ISSUE TITLE
apiClient.modifyTaxonomy is not a function

### ISSUE THREAD

**Issue by meandmyrobot** [kontent-ai/cli#17]
### Brief bug description
Attempting to update a taxonomy group in a CLI script. All other migration scripts are working as intended so my overall setup is fine.

What went wrong?
Check out the test script below. Adding the taxonomy works. I get an error that "apiClient.modifyTaxonomy is not a function" when I try to update it.

```text
An error occurred while running migration: update_taxonomy_test.js see the output from running the script.
Message: apiClient.modifyTaxonomy is not a function
```

### Repro steps

Run the following:

```javascript
const migration = {
    order: 01,
    run: async (apiClient) => {
        // Create a test taxonomy - works
        const addTaxonomyResponse = await apiClient
        .addTaxonomy()
        .withData(
              {
                name: "Test",
                codename: "test_group",
                terms: [{
                    name: "Some Term",
                    codename: "some_term",
                    terms: []
                }],
              },
        )
        .toPromise();    
        
        // Try to modify taxonomy - error 'apiClient.modifyTaxonomy is not a function'
        await apiClient
        .modifyTaxonomy()
        .byTaxonomyCodename('test_group')
        .withData(
            [
              {
                op: 'replace',
                property_name: 'codename',
                value: 'updated_test_group'
              },
            ]
        )
        .toPromise();
    }
};

module.exports = migration;

```

### Expected behavior

The function should exist and the taxonomy should be updated.

### Test environment

 - Platform/OS: MacOS Big Sur 11.0.1
 - Package Dependencies
    - "@kentico/kontent-cli": "0.0.9",
    - "dotenv": "^8.2.0",
    - "faker": "^5.1.0",
    - "rxjs": "^6.6.3"
    - I also have "@kentico/kontent-delivery": "^10.1.0" for some Preview API work
    - In an attempt to fix the issue (and suspecting the management API might need an update - I tried adding "@kentico/kontent-management": "^0.4.7" when I hit the error to see if I needed a newer version of that. This didn't fix my issue.

**Comment by Enngage** [comment]
Hi @meandmyrobot,

The `modifyTaxonomy` query was added in `0.3.20` (https://github.com/Kentico/kontent-management-sdk-js/blob/master/CHANGELOG.md#0320-2020-06-24) of management SDK and this Kontent CLI is using `0.3.19` so you are right that you need an update of the library.

What `package.json` did you update? I assume you didn't forget to run `npm i`  afterwards? 

Nevertheless, this library should be updated to use latest CM SDK version. 

@winklertomas - could you please update dependencies and release new version? It would be nice if you included some publish steps so that others could publish this library too. I could probably force publish myself, but I'm not sure if there are any specific steps / things I should do before / after publish.

**Comment by meandmyrobot** [comment]
Hey,

Apologies. Week #1 of 2021 and getting back into this. I updated Kontent CLI to the latest today (which is listed as 0.0.10). 

On the local project I deleted node modules then reinstalled. I checked the references and I do see 0.0.10 now - but that is bringing in 0.3.19 of @kentico/kontent-management. @winklertomas - am I right that https://github.com/Kentico/kontent-cli/pull/18 didn't publish 0.0.11 (which does have the correct reference)?

So I am now on 0.0.10 and getting a different error running the same script shown above:
Message: call.mapError is not a function

**Comment by winklertomas** [comment]
Hi, the last version is 0.0.10 and it should work with "@kentico/kontent-management": "~0.4.7". I will try your migration script and let you know.

**Comment by meandmyrobot** [comment]
Hi @winklertomas - I got it to work with 0.0.10 by explicitly setting the management API:

```
    "@kentico/kontent-cli": "0.0.10",
    "@kentico/kontent-delivery": "^10.1.0",
    "@kentico/kontent-management": "^0.4.7",
    "dotenv": "^8.2.0",
    "faker": "^5.1.0",
    "rxjs": "^6.6.3"
```
First time I moved to 0.0.10 I didn't explicitly bring in the management API as my project has been working for the past few weeks without it - on https://github.com/Kentico/kontent-cli it didn't mention to install it - and I hadn't needed to as @kentico/kontent-cli brought down a version.

Either way - works now! Thanks for your help. Would you recommend always explicitly installing the two packages together and also installing them locally?

**Comment by winklertomas** [comment]
Hi, sorry for the delay. I've tried @kentico/kontent-cli version 0.0.10 with your script and it worked for me... Have you tried to delete package-lock.json, delete node_modules and run a new npm install? 

`  "dependencies": {
    "@kentico/kontent-cli": "^0.0.10",
    "dotenv": "^8.2.0",
    "rxjs": "^6.5.5"
  },`
  
Actually, there is a transitive dependency on "@kentico/kontent-management@0.3.19" through kontent-backup-manager that wasn't upgraded yet, however, the kontent-cli itself is using "@kentico/kontent-management": "~0.4.7"... So it should be possible to write migration scripts using the new version without the need for explicit install
